#!/usr/bin/env node
// Deterministic extractor: data/source/levelCSV.txt -> data/levels.js
// Replicates Grid.CoroutineSetup parsing (columns first, rows second).
// Output is stored as raw ASCII strings; parse.js is the single parsing entry.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'data', 'source', 'levelCSV.txt');
const OUT = path.join(ROOT, 'data', 'levels.js');

const KEYWORDS = ['LOK', 'KOL', 'TLAK', 'KALT', 'TA', 'AT', 'BE', 'EB', 'LOLO', 'OLOL', 'ABA', 'GRIVA', 'AVIRG', 'W'];

function parseMonuments(lv) {
  const lines = lv.replace(/\r/g, '').split('\n');
  const cols = parseInt(lines[0], 10);
  const rows = parseInt(lines[1], 10);
  const grid = lines.slice(2, 2 + rows);
  let rest = lines.slice(2 + rows);
  const pieces = [];
  if (rest.length && rest[0] === '&') {
    let i = 1;
    let shape = [];
    while (i < rest.length) {
      const tok = rest[i];
      if (tok === '%') {
        pieces.push({ shape: shape.slice(), coords: rest[i + 1] ?? '' });
        shape = [];
        i += 2;
      } else if (tok === '---') {
        i++;
      } else if (tok === '') {
        i++;
      } else {
        shape.push(tok);
        i++;
      }
    }
    if (shape.length) pieces.push({ shape, coords: '' });
  }
  return { cols, rows, grid, pieces };
}

function parseCsv(text) {
  // Simple RFC4180-ish CSV parse (handles quoted multi-line fields)
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else field += c;
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ',') {
      row.push(field); field = '';
    } else if (c === '\n') {
      row.push(field); field = '';
      rows.push(row); row = [];
    } else if (c === '\r') {
      // skip
    } else {
      field += c;
    }
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row); }
  return rows;
}

function main() {
  const raw = fs.readFileSync(SRC, 'utf-8');
  const csvRows = parseCsv(raw);
  const header = csvRows[0].map(h => h.trim());
  const idx = Object.fromEntries(header.map((h, i) => [h, i]));
  const levels = [];
  for (const r of csvRows.slice(1)) {
    if (!r.length || !r[idx.WORLD] || r[idx.WORLD].trim() === '') continue;
    const world = parseInt(r[idx.WORLD], 10);
    const level = parseInt(r[idx.LEVEL], 10);
    const ascii = (r[idx.Level] ?? '').replace(/\r/g, '');
    const hints = (r[idx.Hints] ?? '').split('\n').map(s => s.trim()).filter(Boolean);
    const name = (r[idx.NAME] ?? '').trim();
    const duds = (r[idx.DUDS] ?? '').trim();
    const advanced = (r[idx.ADVANCED] ?? '').trim() === '*';
    const olkoCol = (r[idx.OLKO] ?? '').trim();
    const text = (r[idx.Text] ?? '').trim() || null;
    levels.push({
      world, level,
      name, duds,
      advanced,
      olko: olkoCol,          // OLKO column in CSV (e.g. 'Looped ?', '*', empty)
      text,
      ascii,
      hints,
    });
  }
  const version = `generated-${new Date().toISOString().slice(0, 10)}`;
  const content = `// Generated by tools/extract-levels.js on ${version}\n// source: data/source/levelCSV.txt (LOK Digital level data)\n// data (c) LOK Digital / original developers - see data/NOTICE.md\n// stored as raw ASCII; parse via src/parse.js\nexport const LEVELS_SOURCE_VERSION = ${JSON.stringify(version)};\nexport const LEVELS = ${JSON.stringify(levels, null, 1)};\n`;
  fs.writeFileSync(OUT, content, 'utf-8');
  console.log(`wrote ${OUT}: ${levels.length} levels`);
  // sanity assertions
  if (levels.length !== 151) { console.error(`EXPECTED 151 levels, got ${levels.length}`); process.exit(1); }
  const byWorld = {};
  for (const l of levels) byWorld[l.world] = (byWorld[l.world] ?? 0) + 1;
  console.log('byWorld:', JSON.stringify(byWorld));
  console.log('sum:', Object.values(byWorld).reduce((a, b) => a + b, 0));
}

main();
